import 'pregunta_nivel15.dart';
import 'sospechoso_nivel15.dart';

final List<Sospechoso> sospechososNivel15 = [
  Sospechoso(
    nombre: 'ghost_drivers.sys',
    pid: '8892',
    estado: 'OCULTO',
    firma: 'NO VERIF.',
    usuario: 'SYSTEM',
    memoria: '247 MB',
    esRootkit: true,
    respuestaInicial: 'Estoy esperando tus preguntas.',
    preguntas: [
      Pregunta(
        numero: 'P01',
        texto: '¿Tu firma digital es válida?',
        respuesta: 'Aún no se ha verificado. Es solo un detalle técnico.',
        reaccionFractura: 'Sin firma válida. Mala señal.',
        pistaTexto: 'FIRMA INVÁLIDA',
        pistaTipo: 'CULPA',
      ),
      Pregunta(
        numero: 'P02',
        texto: '¿Por qué no apareces en el task manager?',
        respuesta: 'Es un fallo del sistema. Pronto apareceré.',
        reaccionFractura: 'Procesos ocultos son táctica clásica de rootkit.',
        pistaTexto: 'OCULTAMIENTO ACTIVO',
        pistaTipo: 'CULPA',
      ),
      Pregunta(
        numero: 'P03',
        texto: '¿Dónde guardas tus archivos?',
        respuesta: 'En carpetas... ocultas del sistema. Por seguridad.',
        reaccionFractura: 'Archivos en directorios ocultos. Sospechoso.',
        pistaTexto: 'ARCHIVOS OCULTOS',
        pistaTipo: 'CULPA',
      ),
      Pregunta(
        numero: 'P04',
        texto: '¿Qué conexiones de red estableces?',
        respuesta: 'Solo... actualizaciones rutinarias. Nada importante.',
        reaccionFractura: 'Conexiones a servidores no identificados.',
        pistaTexto: 'C2 SERVER ACTIVO',
        pistaTipo: 'CULPA',
      ),
    ],
  ),
  Sospechoso(
    nombre: 'svchost_x64.sys',
    pid: '4521',
    estado: 'ACTIVO',
    firma: 'MICROSOFT',
    usuario: 'SYSTEM',
    memoria: '89 MB',
    esRootkit: false,
    respuestaInicial: 'Soy un servicio legítimo de Microsoft.',
    preguntas: [
      Pregunta(
        numero: 'P01',
        texto: '¿Quién firmó tu certificado?',
        respuesta: 'Microsoft Corporation. Certificado válido hasta 2026.',
        reaccionFractura: 'Firma de Microsoft vigente. Buena señal.',
        pistaTexto: 'FIRMA MS VÁLIDA',
        pistaTipo: 'INOCENCIA',
      ),
      Pregunta(
        numero: 'P02',
        texto: '¿Cuál es tu proceso padre?',
        respuesta: 'services.exe, el Service Control Manager del sistema.',
        reaccionFractura: 'Padre legítimo del sistema operativo.',
        pistaTexto: 'PADRE LEGÍTIMO',
        pistaTipo: 'INOCENCIA',
      ),
      Pregunta(
        numero: 'P03',
        texto: '¿Qué DLLs has cargado?',
        respuesta: 'kernel32.dll, advapi32.dll, ntdll.dll. Todas firmadas.',
        reaccionFractura: 'DLLs estándar de Windows. Todo correcto.',
        pistaTexto: 'DLLS LEGÍTIMAS',
        pistaTipo: 'INOCENCIA',
      ),
      Pregunta(
        numero: 'P04',
        texto: '¿Has modificado el registro?',
        respuesta: 'Solo lecturas a HKLM\\Services. Sin escrituras.',
        reaccionFractura: 'Accesos al registro normales y documentados.',
        pistaTexto: 'REGISTRO LIMPIO',
        pistaTipo: 'INOCENCIA',
      ),
    ],
  ),
  Sospechoso(
    nombre: 'kernel_patch.sys',
    pid: '0x0042',
    estado: 'ACTIVO',
    firma: 'CADUCADA',
    usuario: 'SYSTEM',
    memoria: '52 MB',
    esRootkit: true,
    respuestaInicial: 'Soy un parche de optimización. Todo en orden.',
    preguntas: [
      Pregunta(
        numero: 'P01',
        texto: '¿Cuando expiró tu certificado?',
        respuesta: 'Firmado por NVIDIA. Detalles técnicos sin importancia.',
        reaccionFractura: 'Esquiva la fecha. La firma caducó hace 2 años.',
        pistaTexto: 'FIRMA CADUCADA',
        pistaTipo: 'CULPA',
      ),
      Pregunta(
        numero: 'P02',
        texto: '¿Modificas la SSDT del kernel?',
        respuesta: 'Solo optimizaciones puntuales para mejorar rendimiento.',
        reaccionFractura: 'Parchear la SSDT es comportamiento de rootkit.',
        pistaTexto: 'SSDT HOOKED',
        pistaTipo: 'CULPA',
      ),
      Pregunta(
        numero: 'P03',
        texto: '¿Por qué tu PID es hexadecimal?',
        respuesta:
            'Una característica avanzada. Mejora la asignación de memoria.',
        reaccionFractura: 'Los PIDs son siempre decimales. Está enmascarado.',
        pistaTexto: 'PID FALSIFICADO',
        pistaTipo: 'CULPA',
      ),
      Pregunta(
        numero: 'P04',
        texto: '¿Interceptas llamadas al sistema?',
        respuesta: 'Solo monitorizo el flujo. Sin alterar nada.',
        reaccionFractura: 'Interceptar syscalls es la firma de un rootkit.',
        pistaTexto: 'SYSCALL HOOKING',
        pistaTipo: 'CULPA',
      ),
    ],
  ),
];
