// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOT7p8wcqdJzOO_lQA_vaklIh2YbBECko',
    appId: '1:848558525196:web:475bca351987974373d729',
    messagingSenderId: '848558525196',
    projectId: 'cyberops-62682',
    authDomain: 'cyberops-62682.firebaseapp.com',
    storageBucket: 'cyberops-62682.firebasestorage.app',
    measurementId: 'G-LS5M5K0FNW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXMCrReDrmI0Jdm0hSwJPbOKFiuMoWXg8',
    appId: '1:848558525196:android:54b66cb6a43d6f7c73d729',
    messagingSenderId: '848558525196',
    projectId: 'cyberops-62682',
    storageBucket: 'cyberops-62682.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK9S18JDBCE_AP1ZKlOEOIuayifCbpy9w',
    appId: '1:848558525196:ios:0495058f38b908f673d729',
    messagingSenderId: '848558525196',
    projectId: 'cyberops-62682',
    storageBucket: 'cyberops-62682.firebasestorage.app',
    iosBundleId: 'com.example.cyberOps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDK9S18JDBCE_AP1ZKlOEOIuayifCbpy9w',
    appId: '1:848558525196:ios:0495058f38b908f673d729',
    messagingSenderId: '848558525196',
    projectId: 'cyberops-62682',
    storageBucket: 'cyberops-62682.firebasestorage.app',
    iosBundleId: 'com.example.cyberOps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOT7p8wcqdJzOO_lQA_vaklIh2YbBECko',
    appId: '1:848558525196:web:94dc9e073794686573d729',
    messagingSenderId: '848558525196',
    projectId: 'cyberops-62682',
    authDomain: 'cyberops-62682.firebaseapp.com',
    storageBucket: 'cyberops-62682.firebasestorage.app',
    measurementId: 'G-729TJ7YRL7',
  );

}